# -*- coding: utf-8 -*-
"""week1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P9C-WIf3fmegFVmYUr5OqgciOU6Gjc5K
"""

import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

fp = '/content/drive/MyDrive/Colab Notebooks/diabetes.csv'

df = pd.read_csv(fp)

display(df)

y = df['Outcome']
y.value_counts()
X = df.drop('Outcome', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state=0)

from sklearn.linear_model import LogisticRegression

my_lr = LogisticRegression(random_state=0)
my_lr.fit(X_train, y_train)

pred_lr = my_lr.predict(X_test)

print ("\n--- Logistic Regression Classifier ---")
print (accuracy_score(y_test, pred_lr))
print (confusion_matrix(y_test, pred_lr))

from sklearn.tree import DecisionTreeClassifier

my_dt = DecisionTreeClassifier(random_state=0)
my_dt.fit(X_train, y_train)

pred_dt = my_dt.predict(X_test)

print ("\n--- Decision Tree Classifier ---")
print (accuracy_score(y_test, pred_dt))
print (confusion_matrix(y_test, pred_dt))

from sklearn.ensemble import RandomForestClassifier

my_rf = RandomForestClassifier(random_state=0)
my_rf.fit(X_train, y_train)

pred_rf = my_rf.predict(X_test)

print ("\n--- Random Forest Classifier ---")
print (accuracy_score(y_test, pred_rf))
print (confusion_matrix(y_test, pred_rf))