# -*- coding: utf-8 -*-
"""week1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yL3DedPJPkJ_UvtUqOmDAv5Bt8GC3e-N
"""

import pandas as pd
import numpy as np
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import mean_squared_error

fp = '/content/drive/MyDrive/Colab Notebooks/breast_cancer.csv'
df = pd.read_csv(fp)

display(df)

df2 = df.drop('label', axis=1)
y = df2['worst compactness']
y.value_counts()
X = df2.drop('worst compactness', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.25, random_state=0)

from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

model = LinearRegression()
model.fit(X_train, y_train)

ly_preds = model.predict(X_test)

print("평균제곱근오차", mean_squared_error(ly_preds, y_test))

from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor()
model.fit(X_train, y_train)
dy_preds = model.predict(X_test)

print("평균제곱근오차", mean_squared_error(dy_preds, y_test))

from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor()
model.fit(X_train, y_train)
ry_preds = model.predict(X_test)

print("평균제곱근오차", mean_squared_error(ry_preds, y_test))